# Generated by Django 2.2.7 on 2019-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Quản lý giáo viên'},
        ),
    ]
