# Generated by Django 2.2.7 on 2019-12-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Quản lý account'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
