# Generated by Django 2.2.7 on 2019-12-17 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20191216_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be alphanumberic or contain number', regex='^[a-zA-Z0-9.+-]*$')]),
        ),
    ]
