# Generated by Django 2.2.7 on 2019-12-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_code', models.AutoField(primary_key=True, serialize=False)),
                ('absent_status', models.BooleanField(default=False)),
                ('image_data', models.FileField(upload_to='media/students/images/}')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='Course name', max_length=50)),
                ('start_day', models.DateTimeField(null=True)),
                ('end_day', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('schedule_date', models.DateTimeField(auto_now_add=True)),
                ('schedule_numberof_day', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
    ]
