# Generated by Django 2.2.7 on 2019-12-14 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_code', models.AutoField(primary_key=True, serialize=False)),
                ('absent_status', models.BooleanField(default=False)),
                ('image_data', models.FileField(upload_to='media/students/images/}')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='Course name', max_length=50)),
                ('start_day', models.DateTimeField(null=True)),
                ('end_day', models.DateTimeField(null=True)),
                ('day_of_week', models.CharField(choices=[('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], default='2', max_length=3)),
                ('time_start_of_course', models.CharField(choices=[('1', 'Tiết 1'), ('2', 'Tiết 2'), ('3', 'Tiết 3'), ('4', 'Tiết 4'), ('5', 'Tiết 5'), ('6', 'Tiết 6'), ('7', 'TIết 7'), ('8', 'Tiết 8'), ('9', 'Tiết 9'), ('10', 'Tiết 10')], default='1', max_length=10)),
                ('time_duration', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Courses List',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('schedule_date', models.DateTimeField(auto_now_add=True)),
                ('schedule_number_of_day', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
    ]
