# Generated by Django 2.2.7 on 2019-12-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_room',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
