# Generated by Django 2.2.7 on 2019-12-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191208_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses List'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Schedule'},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_numberof_day',
            new_name='schedule_number_of_day',
        ),
    ]
