# Generated by Django 2.2.7 on 2019-12-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191216_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
