# Generated by Django 2.2.7 on 2019-12-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191214_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Quản lý điểm danh'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Quản lý Lớp học'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Quản lý buổi học'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='day_of_week',
            field=models.CharField(choices=[('2', 'Thứ hai'), ('3', 'Thứ ba'), ('4', 'Thứ tư'), ('5', 'Thứ năm'), ('6', 'Thứ sáu'), ('7', 'Thứ bảy'), ('8', 'Chủ nhật')], default='2', max_length=3),
        ),
        migrations.CreateModel(
            name='ScheduleImagesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.FileField(upload_to='media/')),
                ('image_date_upload', models.DateTimeField(auto_now_add=True, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Schedule')),
            ],
        ),
    ]
