# Generated by Django 2.2.7 on 2019-12-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191219_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
