# Generated by Django 2.2.7 on 2019-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20191219_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduleimagesdata',
            name='image_date_upload',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
