# Generated by Django 2.2.7 on 2019-12-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_attendance_checked_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='image_data',
            field=models.FileField(null=True, upload_to='media/students/images/}'),
        ),
    ]
