# Generated by Django 2.2.7 on 2019-12-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191222_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
