# Generated by Django 2.2.7 on 2019-12-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191219_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(),
        ),
    ]
