# Generated by Django 2.2.7 on 2019-12-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20191222_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='checked_status',
        ),
    ]
