# Generated by Django 2.2.7 on 2019-12-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20191219_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
