# Generated by Django 2.2.7 on 2019-12-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
