# Generated by Django 2.2.7 on 2019-12-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
    ]
